apiVersion: v1
kind: Service
metadata:
  name: simple-nginx
spec:
  ports:
  - port: 80
  selector:
    app: simple-nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-nginx
  template:
    metadata:
      labels:
        app: simple-nginx
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: beta.kubernetes.io/os
                operator: In
                values:
                - linux
      containers:
      - image: simple-nginx
        imagePullPolicy: Never
        name: simple-nginx-fe
        ports:
        - containerPort: 80
